// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoS3Bt2ZvpjTrFj9sObNrkDB8Y9q3Z1yk',
    appId: '1:778943041305:web:23ddafb5188dd66f4cbf88',
    messagingSenderId: '778943041305',
    projectId: 'authtutorial-1743a',
    authDomain: 'authtutorial-1743a.firebaseapp.com',
    storageBucket: 'authtutorial-1743a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6TfxNS37Xs7iwrkCgN0l4sF76jSiJC3A',
    appId: '1:778943041305:android:e8c66065b3ca5ef84cbf88',
    messagingSenderId: '778943041305',
    projectId: 'authtutorial-1743a',
    storageBucket: 'authtutorial-1743a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZc-gAxvJqeHoLwS6IRbFmI1y8R9hzfjA',
    appId: '1:778943041305:ios:28faa021a741c9aa4cbf88',
    messagingSenderId: '778943041305',
    projectId: 'authtutorial-1743a',
    storageBucket: 'authtutorial-1743a.appspot.com',
    iosClientId: '778943041305-v3o4q9u3ko9qq657sim661kllb769lum.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZc-gAxvJqeHoLwS6IRbFmI1y8R9hzfjA',
    appId: '1:778943041305:ios:452eb2f3acafa25b4cbf88',
    messagingSenderId: '778943041305',
    projectId: 'authtutorial-1743a',
    storageBucket: 'authtutorial-1743a.appspot.com',
    iosClientId: '778943041305-lih35muivbdg4ncl8ctnl48lki9kfk9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterauthentication.RunnerTests',
  );
}
